### ISSUE TITLE
Include results for pik

### ISSUE THREAD

**Issue by jrmuizel** [WyohKnott/image-formats-comparison#3]
Google has a new image codec called [pik](https://github.com/google/pik) that they're working on. According to https://encode.ru/threads/2814-Psychovisual-analysis-on-modern-lossy-image-codecs the results are quite good. It would be great to have it included here.

**Comment by jyrkialakuijala** [comment]
The psychovisual model that PIK uses is not compatible with SSIM, PSNR-HVS-M and many others. One needs to actually look at the images or uses butteraugli to get indicative results.

**Comment by WyohKnott** [comment]
I'll look into it, last time, I had issue compiling it.

**Comment by jan-wassenberg** [comment]
Please let us know what issues you encounter and which compiler - preferably via [Github issue](http://github.com/google/pik/issues) :)

**Comment by WyohKnott** [comment]
@jan-wassenberg Thanks, it is working fine with the latest git.

It seems computationally intensive, I don't know when I will have the time to include it.

**Comment by jan-wassenberg** [comment]
@WyohKnott Thanks for letting us know!
Yes, we haven't optimized the encoder yet, it will be much faster in future.

**Comment by jyrkialakuijala** [comment]
https://encode.ru/threads/2814-Psychovisual-analysis-on-modern-lossy-image-codecs?p=54577&viewfull=1#post54577

shows that for two images pik wins with a huge margin on butteraugli, and gives okeyish results on ssimulacra.

PIK encoding shouldn't be a lot slower than AV1, but there is a bug that leads sometimes to infinite looping at distances smaller than 0.75 or so. Perhaps you were hit by this bug. We have a fix for this and will fix the opensource repo next week.

PIK is not all just about slowness and infinite looping :-) ... PIK's decoding is about 200x faster than AV1, and we have a fast mode that compresses 15 Mpixels/second -- just not accessible by the command line yet. We try to add that too next week to the command line.

**Comment by khavishbhundoo** [comment]
I would like to add more context to @jyrkialakuijala  comment.

I just  refresh the results again with new pik(updated 3 days ago).There was a lot of commit related to performance and the infinite loop occurring at maxerror 0.5 is now fixed.

New result with latest pik : https://encode.ru/threads/2814-Psychovisual-analysis-on-modern-lossy-image-codecs?p=54583&viewfull=1#post54583

As far as encoders are concerned , i used the latest version for each encoder and with the help of the authors i was able to find the optimal flags for each encoder( optimized for best image quality ).

Bash script : https://github.com/khavishbhundoo/Psychovisual-analysis-on-modern-lossy-image-codecs/blob/master/compression_test.sh

**Comment by WyohKnott** [comment]
Pik has now been added.
