### ISSUE TITLE
Copyright question

### ISSUE THREAD

**Issue by Renato4ka** [WyohKnott/image-formats-comparison#5]
Hello,

I would like to use your photos from this project for my research work. Could you please let me know if I can do it and what is the best way to cite your work in our publication?

Best regards,
Renata

**Comment by WyohKnott** [comment]
The images are not mine, they are available from Xiph: http://people.xiph.org/~tterribe/daala/

All images come originally from Wikipedia under a CC license:

These images were created by downsampling very high resolution JPEGs from
Wikipedia. Most are available under a Creative Commons license, and all are
believed to be redistributable, however many require attribution. Please see
the page corresponding to each file for the required attribution and licensing
information.

See https://github.com/WyohKnott/image-formats-comparison/blob/gh-pages/cite_images.txt
